### ISSUE TITLE
طراحی دامنه محور چیست؟

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#1]
یه تعریف از طراحی دامنه محور ارائه بدین که بهتر با هم این مدل طراحی رو بشناسیم.

* لطفا لینک نذارید

**Comment by niloo90** [comment]
به نظر من یه تعریف ساده میتونه این باشه که طراحی دامنه محور (DDD) یه رویکرد تحلیل و توسعه نرم افزاره که تمرکز اصلیش روی شناخت دامنه مساله (کسب و کار) ماست و هدف اصلیش تولید یک نرم افزار ماژولار و منطبق با کسب و کاره که به راحتی قابلیت توسعه پیدا کردن رو داره

**Comment by thisisnabi** [comment]
بنظر منم طراحی دامنه محور حول دانش کسانی که از اون نرم افزار استفاده کنن می چرخه و تمرکز اصلیش روی پیچیدگی های بیزینسه و روی موارد غیر ضروری انرژی از تیم توسعه هدر نمیده.

**Comment by zohrehzamani** [comment]
طراحی دامنه محور راهکاری برای حل پیچیدگی نرم افزاره، که با درک نیاز واقعی کسب و کار مشتری در نهایت منجر به ارائه ی الگوی مناسب پیاده سازی نرم افزار می شود.

**Comment by hadisadibkia** [comment]
به نظر منم DDD، راهکارهایی برای کاهش پیچیدگی های نرم افزار ارائه میده و فقط برای سیستم های پیچیده کاربرد داره (یعنی سیستم هایی با اجزای زیاد و ارتباطات بین این اجزا). این کاهش پیچیدگی از طریق رسید به زبان مشترک بین تیم توسعه و Domain expert انجام میشه و همینطور از طریق تعامل مداوم بین تیم توسعه و متخصص کسب و کار باعث میشه در طول توسعه، ابهامات رفع بشن. همینطور باعث میشه کدنویسی با دقت بیشتری انجام بشه و کدی که نوشته میشه هم به راحتی قابل تست کردن باشه.

**Comment by mahlasa** [comment]
معماری DDD، یک معماری بسیار مستحکم و قدرمند نرم افزاری می باشد که برای پروژه هایی با پیچیدگی های فراوان طراحی شده است. در این معماری پایین ترین لایه دیتابیس یا داده نمی باشد. بلکه پایین ترین لایه منطق های اصلی پروژه می باشد.

**Comment by thisisnabi** [comment]
> معماری DDD، یک معماری بسیار مستحکم و قدرمند نرم افزاری می باشد که برای پروژه هایی با پیچیدگی های فراوان طراحی شده است. در این معماری پایین ترین لایه دیتابیس یا داده نمی باشد. بلکه پایین ترین لایه منطق های اصلی پروژه می باشد.

فکر کنم کلمه معماری باید تغییر کنته توی این پاراگراف

**Comment by Raminafsharnia** [comment]
واقعا توضیحات عالی بودند
