### ISSUE TITLE
چند مزیت طراحی دامنه محور رو نام ببرید؟

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#2]
بنظر شما استفاده از این مدل طراحی چه مزیت هایی برای سازمان، مشتری، و تیم توسعه بهمراه داره؟

* لطفا لینک نذارید

**Comment by monirtatar** [comment]
زبان مشترک بین بیزینس و توسعه منجر به تعاملات بهتر و درک دقیق و شفاف مساله میگردد 
سهولت توسعه پذیری و اعمال تغییرات
سهولت نگهداشت 
قابلیت استفاده مجدد
کمک به شناخت و درک مساله برای اعضای جدید تیم توسعه

**Comment by thisisnabi** [comment]
با توجه به آمار هایی که هست، طراحی دامنه محور در سیستم های پیچیده کیفیت قابل قبولی رو تضمین میکنه
با توجه به این که تمرکز روی بیزینس هست، زمان صرف کار های جانبی نمیشه
دانش بیزینس سیستم توی تیم توسعه پخش میشه و این از قدرت زبان مشترکه

**Comment by zohrehzamani** [comment]
در پروژه ھای نرم افزاری، دغدغه ی اصلی تیم توسعه، طراحی دقیق و درست فرآیند ھا و قوانین نرم افزار هست، و زمان و ھزینه ای که صرف تحلیل، پیاده سازی و تست فرآیندھا و بیزینس نرم افزار میشه خیلی بیشتر از زمان و ھزینه ای است که صرف موارد فنی و زیر ساخت نرم افزاری پروژه میشه؛ بخاطر همین بهترین مزیت استفاده از DDD میتونه این باشه که هرچند در فاز شناخت اولیه ی کسب و کار هزینه ی زمانی و مالی بیشتری میشه ولی در ادامه ی توسعه ی نرم افزار با رعایت راهکارها و الگوهایی که از DDD بدست میاریم این هزینه ها رو کاهش بدیم و تا حد زیادی از پیاده سازی درست فرآیندها اطمینان حاصل میشه.

**Comment by hadisadibkia** [comment]
1- رسیدن به زبان مشترک بین تیم توسعه و Domain Expert
2- کاهش پیچیدگی های نرم افزار از طریق خرد کردن مساله اصلی (Domain) به مساله های کوچکتر (Sub Domain)
3- اینکه هر Sub Domain خودش میتونه شامل n تا Bounded Context باشه باعث میشه که هر بخشی به صورت مجزا پیاده سازی بشه و تاثیری روی بقیه بخش ها نداشته باشه و این خودش انعطاف سیستم رو بیشتر می کنه و باعث میشه نگهداشت هم با کیفیت بالاتری انجام بشه.

**Comment by monirtatar** [comment]
همونطور که حدیث گفت شکستن مساله به بخشهای جدا و مستقل امکان پیاده سازی مجزا رو میده که میتونه دو تا مزیت داشته باشه
- توسعه موازی و همزمان بخشها
- هر بخش میتونه معماری و تکنولوژی متفاوتی داشته باشه

به نظر مهمترین مزیت DDD اینه که تمام تلاشهای پروژه و تمرکز اصلی تیم توسعه فارغ از ابزار و تکنولوژی، صرف مشکلات و پیچیدگی های دامین (بیزینس،فلسفه وجودی محصول) میشه

**Comment by mahlasa** [comment]
یکی از اهداف DDD تحلیل و توسعه مفاهیم به صورت "دامنه محور "با توجه به نیازمندی های کارفرما می باشد و پیروی آن تمرکز بروی پیچیدگی ها می باشد. همچنین سیستم ها به صورت ServiceBase ,SystemBase پیاده سازی می شوند. حال با توجه به دامنه محور بودن اساس DDD، هزینه تحلیل و توسعه بیشتر از متدولوژی موجود می باشد، اما تضمین کیفیت و نگهداشت مطمئن تر را به ارمغان می آورد.

**Comment by thisisnabi** [comment]
> یکی از اهداف DDD تحلیل و توسعه مفاهیم به صورت "دامنه محور "با توجه به نیازمندی های کارفرما می باشد و پیروی آن تمرکز بروی پیچیدگی ها می باشد. همچنین سیستم ها به صورت ServiceBase ,SystemBase پیاده سازی می شوند. حال با توجه به دامنه محور بودن اساس DDD، هزینه تحلیل و توسعه بیشتر از متدولوژی موجود می باشد، اما تضمین کیفیت و نگهداشت مطمئن تر را به ارمغان می آورد.

این کلمات SystemBase و ServiceBase بیان زیبایی از اینکه لزوما سیستم قرارنیست سرویس گرا پیاده سازی بشه.
