### ISSUE TITLE
اشتباهات رایج در رسیدن به طراحی دامنه محور چیست؟

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#3]
با توجه به اینکه استفاده از این مدل طراحی چالش های خاص خودش رو به همراه داره، چند تا از این چالش ها رو می تونید اسم ببرید

* لطفا لینک نذارید

**Comment by niloo90** [comment]
یکی از چالش هاش میتونه تشخیص نادرست استفاده از این طراحی توی پروژه هامون باشه
طراحی دامنه محور روی پروژه هایی با حوزه ی کسب و کاری پیچیده کاربرد داره و اگه روی پروژه هایی با کسب و کار ساده استفاده بشه، اشتباهه
 
یکی دیگه از چالش هاش به نظرم همون بخش شناخت کسب و کاره، وقتی با کسب و کار پیچیده طرفیم قطعا گام شناختش میتونه خیلی پر چالش و زمانبر باشه

**Comment by thisisnabi** [comment]
- بنظر منم یکی از اشتباهات این دیدگاه می تونه این باشه که واسه رسیدن به کیفیت، بهتره برای همه پروژه ها از DDD استفاده کرد.
- یکی دیگه از این اشتباهات اینه که قبل رسیدن به زبان مشترک و ساخت Object-Model ، کد کردن نیاز یا همون شروع پیاده سازیه.
- میشه گفت انتخاب Domain Expert مناسب هم چالش برانگیزه، چون قراره که روی گفته های ایشون بزنیم به دل دریا.
- ایجاد زبان مشترک در ابتدای شروع نیست، با توجه به ذات تغییر پذیری نرم افزار، بروز رسانی زبان مشترک مهمه و نباید در طول زمان اهمیتش کم رنگ بشه.

**Comment by hadisadibkia** [comment]
به نظر من زمان بر بودن تعاملاتی که لازمه شروع استفاده از DDD هست یکی از معایبشه و همینطور طبق کامنت نیلوفر، اینکه برای کسب و کارهایی که پیچیدگی زیادی دارن مناسبه و لزومی به استفاده از DDD حتی توی حوزه های غیر پیچیده نیست چون اصل DDD کمک به رفع پیچیدگی ها هستش.

**Comment by monirtatar** [comment]
- استفاده از DDD برای پروژه های که پیچیدگی دامنه بالایی ندارند و تغییرات و توسعه آتی ندارند مناسب نیست
- شروع زود هنگام فاز پیاده سازی و درگیر شدن در مسایل تکنولوژی
- عدم سهولت و ارتباط مداوم تیم توسعه با متخصصین دامنه،  یکی از چالشهاست
من متوجه منظور نبی از (میشه گفت انتخاب Domain Expert مناسب هم چالش برانگیزه،) نشدم؟

**Comment by mahlasa** [comment]
همونطور که در جلسه اول این موضوع بیان شد، بنظرم چالش اول در مواجه با نیازمندی ها کارفرما، این است که تا چه مرحله ای به شکست دامنه و زیردامنه ها پرداخته شود .
از دیگر چالش ها اخذ تمامی دیتاها و بیزینس از کارفرما به صورت کامل و شفاف می باشد که این بخش باید توسط فردی متخصص با توجه به چیستی مسئله انجام شود.

**Comment by thisisnabi** [comment]
> * استفاده از DDD برای پروژه های که پیچیدگی دامنه بالایی ندارند و تغییرات و توسعه آتی ندارند مناسب نیست
> * شروع زود هنگام فاز پیاده سازی و درگیر شدن در مسایل تکنولوژی
> * عدم سهولت و ارتباط مداوم تیم توسعه با متخصصین دامنه،  یکی از چالشهاست
>   من متوجه منظور نبی از (میشه گفت انتخاب Domain Expert مناسب هم چالش برانگیزه،) نشدم؟

در سیستم هایی که مشتری شخصی نداره و خود شرکت ها برای عموم توسعه میدن چنین مسئله ای پیش میاد که خب الان کیا خبره این کارن!

**Comment by mahlasa** [comment]
> > * استفاده از DDD برای پروژه های که پیچیدگی دامنه بالایی ندارند و تغییرات و توسعه آتی ندارند مناسب نیست
> > * شروع زود هنگام فاز پیاده سازی و درگیر شدن در مسایل تکنولوژی
> > * عدم سهولت و ارتباط مداوم تیم توسعه با متخصصین دامنه،  یکی از چالشهاست
> >   من متوجه منظور نبی از (میشه گفت انتخاب Domain Expert مناسب هم چالش برانگیزه،) نشدم؟
> 
> در سیستم هایی که مشتری شخصی نداره و خود شرکت ها برای عموم توسعه میدن چنین مسئله ای پیش میاد که خب الان کیا خبره این کارن!

 حتی میتوان یک تیم از افراد متخصص در این زمینه تشکیل داد و ساختار و دستورالعمل تهیه کرد و از یک فیلتر رد شده تا تاییدات انجام شود، به عنوان مثال در سازمان خودمون، از آقای زارع به عنوان مرجع اطلاعاتی در اکثر بیزینس های رایج و حتی تخصصی تر می توان بهره برد و اسکوپ یک کسب و کار را مشخص نمود.

**Comment by monirtatar** [comment]
با توجه به توضیحات دوستان به نظر من انتخاب domain Expert چالش تیم توسعه نمیتونه باشه
در واقع راه کارهای DDD بعد از مشخص شدن اسکوپ کار هست.

و انتخاب بیزینس/دومین  و آنچه قرار هست انجام شود توسط ذینفع تعیین میشه. 

اتفاقا تاکید اصلی DDD هم بر این هست که دقیقا چیزی رو تولید و توسعه بدیم که واقعا در بیزینس در جریان هست.
به طور مثال سیستم های حقوق دستمزد مختلفی ممکنه وجود داشته باشه و در شرکت ما مثلا فلان نوع، قرار هست تولید و توسعه داده بشه که انتخابش با ذینفعان، مثلا اقای زارع یا مشتری خاص.

و بعدشdomain Expert ما میشه کسی که عملا داره با این نوع سیستم حقوق دستمزد کار میکنه

**Comment by thisisnabi** [comment]
> با توجه به توضیحات دوستان به نظر من انتخاب domain Expert چالش تیم توسعه نمیتونه باشه در واقع راه کارهای DDD بعد از مشخص شدن اسکوپ کار هست.
> 
> و انتخاب بیزینس/دومین  و آنچه قرار هست انجام شود توسط ذینفع تعیین میشه.
> 
> اتفاقا تاکید اصلی DDD هم بر این هست که دقیقا چیزی رو تولید و توسعه بدیم که واقعا در بیزینس در جریان هست. به طور مثال سیستم های حقوق دستمزد مختلفی ممکنه وجود داشته باشه و در شرکت ما مثلا فلان نوع، قرار هست تولید و توسعه داده بشه که انتخابش با ذینفعان، مثلا اقای زارع یا مشتری خاص.
> 
> و بعدشdomain Expert ما میشه کسی که عملا داره با این نوع سیستم حقوق دستمزد کار میکنه

بله درسته ولی توی سیستم هایی که عمومی هستند شما نمی تونی عموم کاربران رو بیاری به عنوان متخصص دامنه. پس ناچاری نفر(هایی) رو انتخاب کنی. انتخاب معمولا آبستن چالش هست.
