### ISSUE TITLE
 آیا مدل دامنه فقط دانش متخصص دامنه را نشان می دهد (مدل می کند)؟

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#4]
_مدل دامنه نمی دونم ترجمه درستی باشه که گذاشتم ولی منظور ما Domain Model هستش._

- لطفا لینک نذارید

**Comment by niloo90** [comment]
به نظرم بله
یعنی اگه اینجوری تعریف کنیم که ما از domain Expert یک سری دانش و اطلاعات پراکنده به دست اوردیم، حالا باید با یه فرایندی این دانش رو سازماندهی کنیم به طوری‌ که‌ برای همه قابل فهم و ملموس باشه که عملا خروجی این فرایند domain model ما میشه
پس به نظرم میشه گفت domain model دانش اون متخصص دامنه ( domain expert) رو مدل میکنه

**Comment by hadisadibkia** [comment]
به نظر من مدل دامنه شاید دقیقا منطبق با دانش متخصص دامنه نباشه. شاید بعد از اینکه اطلاعاتی رو از متخصص دامنه دریافت کردیم، نیاز به پردازش و فیلتر و ساده سازی اون اطلاعات داشته باشیم و مدل دامنه ای که طراحی میکنیم شاید انطباق کامل با دانش فعلی متخصص دامنه نداشته باشه.
ولی کلیت مدل، منطبق با دانش متخصص دامنه هست.

**Comment by mahlasa** [comment]
مدل دامنه در طی مراحل جمع آوری کسب و کار و نیازمندی ها، میتونه تبدیل به دانش مختص دامنه بشه، چرا که در چرخه تکمیل شدن اطلاعات هر دامنه این اتفاق رخ میدهد و تبدیل به مدلی از دامنه میشود.

**Comment by hamedebtekar** [comment]
از اونجایی که مدل دامنه از یک  دانش همگانی است،
 مدل دامنه باید نتیجه یک فرآیند باشه که در اون همه اعضای تیم برای بحث در مورد مشکلی که با اون روبرو هستند و چگونگی حل آن جلسه بزارن.
این همکاری و جلسات بین متخصصین دامنه و تیم توسعه برای موفقیت پروژه بسیار مهمه و مدل دامنه باید نحوه تفکر شما در مورد پروژه و تمام دانش حاصل از اون جلسات همکاری رو نشون بده. هر زمان که نیاز به تصمیم گیری در طول پروژه هم باشه، همه باید به مدل دامنه مراجعه کنن تا به دنبال جوابش باشن یا سعی کنند به طور مکرر طرح رو تکمیل کنن تا مواردی رو پیدا کنن که قبلا ازش خبر نداشتن . پس جواب سوال شما برای اینکه مدل فقط بر اساس دانش متخصص دامنه است به نحوی خیر می باشد. اگر جواب بله باشد ، اینجا بحث کشف کردن موارد جدید رو دیگه پوشش نمیده که تو جلسات پیدا میشن

**Comment by zohrehzamani** [comment]
به نظر من مدل دامنه باید به عنوان یک تصویر واضح از مشکلی که در حال حل شدنه و همچنین راه حل پیشنهادی اون باشه. خیلی مهمه که همه ذینفعان پروژه به مدل دامنه کمک کنن تا همه مفاهیم و تعاریف کلیدی پروژه و نحوه برخورد و حل مشکل رو درک کنن.
