### ISSUE TITLE
مسائل مربوط به تقسیم بندی دامنه و زیر دامنه ها

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#5]
دلیل این تقسیم بندی سیستم به زیر دامنه ها چیه؟
تا چه اندازه زیر دامنه می تونیم ایجاد کنیم؟ استاندارد خاصی داره این کار؟
آیا احتمال داره چند Core Domain در سیستم داشته باشیم؟ یا اینکه یک گروه داریم با ماهیت Core Domain که می تونه چندین زیر دامنه (Sub Domain) داشته باشه؟
آیا تمام زیر دامنه های سیستم (در هر گروهی از Core, Supporting, Generic) همه می تونن در یک برنامه (سرویس) پیاده سازی بشن؟

**Comment by hadisadibkia** [comment]
دلیل تقسیم بندی به زیر دامنه، کمک به رفع پیچیدگی دامنه هست و این هستش که با تمرکز بیشتری بتونیم روی هر زیر دامنه کار کنیم و حتی شاید به این نتیجه برسیم که بعضی زیر دامنه ها ارزش اینو ندارن که روشون کار کنیم و باید کنار بذاریمشون.
به نظرم تقسیم بندی به زیر دامنه ها، محدودیت خاصی نداره و با توجه به پیچیدگی دامنه، میتونیم تا هرجایی که لازمه اونو به زیر دامنه ها بشکنیم.
بنظرم core domain یکیه. چون کلید اصلی موفقیت پروژه، موفقیت توی core domain هستش. اصلی ترین زیر دامنه همون Core domain هستش البته ممکنه زیر دامنه های تعیین کننده دیگه ای هم داشته باشیم اما اصلی ترین همیشه یه دونه هست.
زیر دامنه core باید پیاده سازی بشه اما دو زیر دامنه دیگه، باید اهمیتشون تعیین بشه و بر اساس اولویت پیاده سازی بشن و شاید نیاز باشه بعضی موارد ازشون چشم پوشی کنیم.

**Comment by niloo90** [comment]
@hadisadibkia 
با مواردی که گفتی موافقم به جز یه مورد اونم اینکه همیشه یه core domain داریم به نظرم درست نیست، اگه domain مساله بزرگ باشه ممکنه با چند تا core domain طرف باشیم.

**Comment by niloo90** [comment]
@hadisadibkia 
با مواردی که گفتی موافقم به جز یه مورد اونم اینکه همیشه یه core domain داریم به نظرم درست نیست، اگه domain مساله بزرگ باشه فکر کنم ممکنه با چند تا core domain طرف باشیم.

**Comment by niloo90** [comment]
با مواردی که گفتی موافقم به جز یه مورد اونم اینکه همیشه یه core domain داریم به نظرم درست نیست، اگه domain مساله بزرگ باشه فکر کنم ممکنه با چند تا core domain طرف باشیم.

**Comment by niloo90** [comment]
> دلیل تقسیم بندی به زیر دامنه، کمک به رفع پیچیدگی دامنه هست و این هستش که با تمرکز بیشتری بتونیم روی هر زیر دامنه کار کنیم و حتی شاید به این نتیجه برسیم که بعضی زیر دامنه ها ارزش اینو ندارن که روشون کار کنیم و باید کنار بذاریمشون.
> به نظرم تقسیم بندی به زیر دامنه ها، محدودیت خاصی نداره و با توجه به پیچیدگی دامنه، میتونیم تا هرجایی که لازمه اونو به زیر دامنه ها بشکنیم.
> بنظرم core domain یکیه. چون کلید اصلی موفقیت پروژه، موفقیت توی core domain هستش. اصلی ترین زیر دامنه همون Core domain هستش البته ممکنه زیر دامنه های تعیین کننده دیگه ای هم داشته باشیم اما اصلی ترین همیشه یه دونه هست.
> زیر دامنه core باید پیاده سازی بشه اما دو زیر دامنه دیگه، باید اهمیتشون تعیین بشه و بر اساس اولویت پیاده سازی بشن و شاید نیاز باشه بعضی موارد ازشون چشم پوشی کنیم.

با مواردی که گفتی موافقم به جز یه مورد اونم اینکه همیشه یه core domain داریم به نظرم درست نیست، اگه domain مساله بزرگ باشه فکر کنم ممکنه با چند تا core domain طرف باشیم.

**Comment by hamedebtekar** [comment]
بچه ها هرکدام مواردی که گفتید درسته منتها از نظر من در یک پروژه ما یک core domain داریم اما این core ممکنه تو خودش به دامنه ها و زیر دامنه های دیگه تقسیم بشه ، اساسا وجود ۲ core در یک پروژه معنی خاصی شاید نداشته باشه، البته این تعاریف همه ضمنی هستند مهم اینه تو تیم ترجمه یا زبان مشترک ما چگونه برداشتی از دامنه اصلی و زیردامنه ها باشه . اساس تمرکز هم روی core قرار میگیره ، ممکنه بقیه موارد مثل   support  و ... در پروژه اصلا لازم نشه اما core همیشه وجود داره ولی خب خودش از دامنه ها و زیر دامنه هایی تشکیل شده باشه

**Comment by AliAfshar97** [comment]
به طور حتم هر سيستم داراي چندين core domain و sub domain هستند حتي در اثر گذر زمان ممكنه برخي از اين sub domain ها تبديل به core domain بشن يا حتي برعكسش چون برخي روش ها منسوخ ميشن و جاي خودشونو به روش هاي جديد تر ميدهند يا حتي بيزنس ها تغيير ميكنند.
براي پياده سازي ما نميتونيم تمامي موارد رو در يك سيستم جا بدهيم و در صورتي كه امكانش هست بايد اونو به بخش هاي بيشتري تفكيك كنيم دليلشم اينه كه ممكنه در حال حاضر سيستم ما سيستم سبكي باشه و كار باهاش سريعه اما در اثر گذر زمان مطمئنيم كه تغييري نميكنه ؟
ممكنه يه سيستم به ظاهر ساده در سال هاي بعدش به پيچيده ترين تبديل بشه با گستردگيه فراوان

**Comment by niloo90** [comment]
یه نکته بگم، فکر کنم به اشتباهی که اکثرمون میکنیم اینه که توی لفظ بین core domain و sub domain تفاوت قائل میشیم
در واقع core domain خودش یک نوعی از sub domain هست.
ما وقتی یه دامنه رو میشکونیم به چند تا زیر دامنه (sub domain)، یک یا چند تا از این sub domain ها میتونن core باشن باقی میتونن supporting و generic باشن.

**Comment by hamedebtekar** [comment]
> یه نکته بگم، فکر کنم به اشتباهی که اکثرمون میکنیم اینه که توی لفظ بین core domain و sub domain تفاوت قائل میشیم
> در واقع core domain خودش یک نوعی از sub domain هست.
> ما وقتی یه دامنه رو میشکونیم به چند تا زیر دامنه (sub domain)، یک یا چند تا از این sub domain ها میتونن core باشن باقی میتونن supporting و generic باشن.

کاملا درسته اما چون این مفاهیم انتزاعی هستند ما باید تعیین کنیم core کدوم دامنه یا دامنه هاست . و اهمیت تمرکز برای core قرار میگیره .

**Comment by mahlasa** [comment]
طبق تعاریف و جلسات اخیر، sub domain ها به محدوده‌های خاص و قابل تشخیص در یک مسئله بزرگ گفته می شه، حال این که چه زمانی با domain کار داریم و چه زمانی با sub domain کاملا وابسته به دیدگاه و شناخت حوزه کاری کسب و کارمون داره. ممکنه یک sub domainدر یک پروژه، برای پروژه دیگری domain بزرگ باشه و برعکس یک domain در یک پروژه برای پروژه‌ای دیگر sub domainکوچک باشد.
بنظرم مهمترین قسمت و هدف پروژه، تشخیص صحیح و انتخاب core domain است.در واقع در صورتی که انتخاب صحیح داشته باشیم، احتمال موفقیتمون تو  پروژه خیلی بیشتر میشه.
با این حساب، بنظرم هر پروژه یک core domain داره که زیرمجموعه اش domian , sub domain   (چه نوع generic/ چه نوع suppoerting) تشکیل میشه.

**Comment by zohrehzamani** [comment]
در رابطه با CoreDomain  طبق گفته ی اقای Eric Evant
 میگن برای پیدا کردنش به این ۳ سال پاسخ بدهید:
چه چیزی در این سیستم اونقدر ارزشمنده برامون که می خوایم بخاطرش اون سیستم رو بنویسیم؟
چرا از سیستم اماده و از قبل نوشته شده استفاده نمیکنیم؟
چرا برون سپاری نمیکنیم؟
حیاتی و اصلی ترین بخش کسب و کار ما که به بیزینسمون مفهوم رقابتی میده رو در این قسمت باید پیدا کنیم.طوریکه حدودا ۲۰ درصد ارزش کل سیستم رو در بر میگیره.
حالا با توجه به این تعاریف به نظر من در هر SubDomain یک بخش core داریم!!(البته احتمالا موارد استثنا هم داریم) و اینکه همه ی زیر دامنه ها حتما شامل ۳ بخش هستند یا نه رو باید بگم به نظرم بخش generic میتونه گاهی وجود نداشته باشه.
و اینکه تمام زیر دامنه ها میتونن توی یک سرویس پیاده سازی بشن یا نه رو باید بگم خیلی بستگی به اون معماری و الگویی که برای پیاده سازی boundedcontext ها در نظر میگیریم داره و خب به نظر من ما داریم همه ی این زحمتا رو میکشیم که پروژه رو ساده تر کنیم از نظر توسعه، پس احتمالا پیاده سازی همه ی موارد در یک سرویس اشتباهه

**Comment by thisisnabi** [comment]
> در رابطه با CoreDomain طبق گفته ی اقای Eric Evant
> میگن برای پیدا کردنش به این ۳ سال پاسخ بدهید:
> چه چیزی در این سیستم اونقدر ارزشمنده برامون که می خوایم بخاطرش اون سیستم رو بنویسیم؟
> چرا از سیستم اماده و از قبل نوشته شده استفاده نمیکنیم؟
> چرا برون سپاری نمیکنیم؟
> حیاتی و اصلی ترین بخش کسب و کار ما که به بیزینسمون مفهوم رقابتی میده رو در این قسمت باید پیدا کنیم.طوریکه حدودا ۲۰ درصد ارزش کل سیستم رو در بر میگیره.
> حالا با توجه به این تعاریف به نظر من در هر SubDomain یک بخش core داریم!!(البته احتمالا موارد استثنا هم داریم) و اینکه همه ی زیر دامنه ها حتما شامل ۳ بخش هستند یا نه رو باید بگم به نظرم بخش generic میتونه گاهی وجود نداشته باشه.
> و اینکه تمام زیر دامنه ها میتونن توی یک سرویس پیاده سازی بشن یا نه رو باید بگم خیلی بستگی به اون معماری و الگویی که برای پیاده سازی boundedcontext ها در نظر میگیریم داره و خب به نظر من ما داریم همه ی این زحمتا رو میکشیم که پروژه رو ساده تر کنیم از نظر توسعه، پس احتمالا پیاده سازی همه ی موارد در یک سرویس اشتباهه

ممنون بابت توضیحاتت زهره، ۳ تا سواله خیلی برام جذاب بود 
. من فقط سر این موضوع که گفتی در یک سیستم واحد باشه بگم که اشتباه نیست حقیقتا چون ما Modular monolithic  رو هم داریم و اینکه اگر توزیع بدرستی انجام نشه سیستم های توزیع شده به مراتب توسعه پیچیده تری دارن.
