### ISSUE TITLE
مفاهیم بخش استراتژیک طراحی دامنه محور

### ISSUE THREAD

**Issue by thisisnabi** [Hesabrayan/Individual-Development-Plan#6]
موارد زیر قابل تعریف هستند، شما تعریفتون چیه

- Domain Model
- Domain 
- Subdomain  (Core, Supporting, Generic)
- Bounded Context
- Context Mapping

**Comment by niloo90** [comment]
در مورد domain تو حوزه نرم افزار میتونیم بگیم اون  کسب و کاریه که داریم براش نرم افزار رو تولید میکنیم، عملا دانشی که توی اون کسب و کار هست

ولی یه تعریف عمومی ازش دیدم هم دید جالبی میداد، اینکه هر مرز دلخواهی از مفاهیم توی جهان میتونه تشکیل یه دامنه بده، یعنی مهم اون مرزبندی ماست، مفاهیم رو میشه به شیوه های مختلفی مرزبندی کرد که اینجوری دامنه های مختلفی ایجاد میشه
مثالش رو هم میگم چون خوشم اومد از مثالش :)
میگفت فرض کنید یه سری اشکال رنگی دارید که هر کدوم یه مفهوم در جهانن
میتونیم بیایم اشکال آبی رو یه دامنه بگیریم، اشکال سبز رو یه دامنه بگیریم و ...
ولی یه نگاه دیگه اینه که میتونیم مثلثها رو یه دامنه بگیریم، مربع ها رو یه دامنه بگیریم و ...
اینجوری یه مفهوم مثلث آبی بسته به نگاه ما میتونه توی دو تا دامنه قرار بگیره
پس توی دامنه ها مهم مرزبندی ما از مفاهیمه

**Comment by hadisadibkia** [comment]
1. منظور از Domain model، مدل کردن دانش متخصص دامنه بعد از پردازش و فیلتر و ساده سازیشه.
2. Domain همون کسب و کار اصلی و کلی هستش
3. زیر دامنه، به معنی شکستن دامنه به بخش های کوچیکتره که بر اساس اینکه کدوم بخش، بخش اصلیه، به عنوان Core تعیین میشه. generic معمولا تو بسیاری از کسب و کارها مشترکه مثل امکان گزارش گیری و Supporting هم اگر نباشه، یه جای کار میلنگه و ناقصه.
4. برای اینکه پیچیدگی های هر زیر دامنه به زیر دامنه های دیگه نشت نکنه، باید یه مرزبندی قائل بشیم براش که بهش میگیم Bounded context. که ارتباط هر زیر دامنه با Bounded context معمولا یک به یکه اما الزاما اینجوری نیست و ممکنه هر زیر دامنه، n تا Bounded context داشته باشه.
5. مدل تصویری ارتباط Bounded context ها باهم، همون Context mapping هستش.

**Comment by mahlasa** [comment]
دامنه بیانگر حوزه کلی کسب و کار یک برنامه است، بدین صورت که ممکنه در یک سازمان چندین دامنه وجود داشته باشه که به صورت مفهومی بایکدیگر ارتباط دارند و بعد از درک کامل کسب و کار یک سازمان می تونیم دامنه را مدل کنیم حال این مدلسازی باید به صورت تخصصی باید انجام شه و به گونه ای باشه که قابل درک برای تمامی اعضای پروژه باشه.
تمامی دامنه ها دارای زیردامنه هستند، بدین صورت که با استفاده از زیردامنه ها میتونیم چالش ها پروژه و سختی کار را تقسیم کنیم.

**Comment by mahlasa** [comment]
برای سایر مواردی که ذکر شده خودم خیلی نتونستم تعریف قابل درکی داشته باشم. بقیه دوستان اگه تعریف دقیق تری دارین ارائه بدین.ممنون

**Comment by Karimibehrang** [comment]
ممنون از مشارکتتون بسیار عالی

**Comment by zohrehzamani** [comment]
مفاهیم Domain  و Subdomain  رو که همه خیلی عالی تعریف کردن و برامون جا افتاد. من در رابطه با BoundedContext می خوام بگم. 
میگن اگر SubDomain  صورت مسئله است، BoundedContext راه حل اون مسئله است.
هر مسئله قطعا یه راه حل داره! و خب طبیعیه که برای یک مسئله بیش از یک راه حل هم ممکنه داشته باشیم.
و راه حل ها میتونن کاملا متفاوت از هم(منطور از نظر تکنولوژی و بستر بانک اطلاعاتی است) باشند.
