### ISSUE TITLE
انتخاب مساله در حوزه منابع انسانی جهت اجرای مفاهیم DDِD

### ISSUE THREAD

**Issue by niloo90** [Hesabrayan/Individual-Development-Plan#8]
طبق صحبت هایی که داشتیم قرار بر این شد در حوزه منابع انسانی، مساله ای رو طرح کنیم که بتونیم موضوعاتی که در جلسات DDD روی اونها بحث میکنیم رو به صورت تمرینی روی اون مساله پیاده کنیم تا موضوعات برامون شفاف تر و قابل درک تر بشن.
برای انتخاب مساله من یه توضیح کلی از نیازمندی های اصلی میدم که محدوده کلی مشخص بشه، ولی باید با همفکری همدیگه یه بخش کوچیکی رو به عنوان مساله انتخاب کنیم تا مفاهیم هر جلسه روی اون بخش جلو ببریم.

**شرح نیازمندی:**
فرایند منابع انسانی شامل چهار مرحله اصلی میشه: 1- پروسه قبل از ورود پرسنل به سازمان 2- پروسه ورود پرسنل به سازمان 3- پروسه حضور پرسنل در سازمان 4- پروسه خروج پرسنل از سازمان

ما نیاز به سیستمی داریم که مرحله سوم از این فرایند (پروسه حضور پرسنل در سازمان) رو برامون مدیریت کنه.
در پروسه حضور پرسنل در سازمان ما با مسائل زیر درگیریم:
1- تشکیل پرونده پرسنلی (اطلاعات شناسنامه ای، سوابق تحصیلی، سوابق کاری، سوابق آموزشی و ...)
2- مدیریت احکام (مبنای محاسبات حقوقی، ارتقاء شغلی و ...)
3- مدیریت عملکرد اداری ماهیانه (کارکرد یا تایم شیت، مرخصی، ماموریت و ...)
4- مدیریت عملکرد مالی (مدیریت پرداخت ها شامل حقوق، مساعده، وام و ... )
5- و ...
چهار بخش اشاره شده برای ما توی اولویت هستن. 

حالا بر اساس توضیحات اولیه بالا میتونیم یه بخش کوچکتری رو انتخاب کنیم و روی اون پیش بریم. لطفا هر کسی نظرش رو بگه و اگه نیاز به توضیحات بیشتر هست بگین تا روشنتر بشه موضوع.
حتی به نظرم مفاهیم جلسه دوم (دامنه و زیر دامنه) رو میشه روی همین توضیحاتی که دادم پیش ببریم و یکی از زیر دامنه هایی که تشخیص میدیم رو برای مفاهیم جلسات بعدی انتخاب کنیم.

**Comment by thisisnabi** [comment]
> طبق صحبت هایی که داشتیم قرار بر این شد در حوزه منابع انسانی، مساله ای رو طرح کنیم که بتونیم موضوعاتی که در جلسات DDD روی اونها بحث میکنیم رو به صورت تمرینی روی اون مساله پیاده کنیم تا موضوعات برامون شفاف تر و قابل درک تر بشن. برای انتخاب مساله من یه توضیح کلی از نیازمندی های اصلی میدم که محدوده کلی مشخص بشه، ولی باید با همفکری همدیگه یه بخش کوچیکی رو به عنوان مساله انتخاب کنیم تا مفاهیم هر جلسه روی اون بخش جلو ببریم.
> 
> **شرح نیازمندی:** فرایند منابع انسانی شامل چهار مرحله اصلی میشه: 1- پروسه قبل از ورود پرسنل به سازمان 2- پروسه ورود پرسنل به سازمان 3- پروسه حضور پرسنل در سازمان 4- پروسه خروج پرسنل از سازمان
> 
> ما نیاز به سیستمی داریم که مرحله سوم از این فرایند (پروسه حضور پرسنل در سازمان) رو برامون مدیریت کنه. در پروسه حضور پرسنل در سازمان ما با مسائل زیر درگیریم: 1- تشکیل پرونده پرسنلی (اطلاعات شناسنامه ای، سوابق تحصیلی، سوابق کاری، سوابق آموزشی و ...) 2- مدیریت احکام (مبنای محاسبات حقوقی، ارتقاء شغلی و ...) 3- مدیریت عملکرد اداری ماهیانه (کارکرد یا تایم شیت، مرخصی، ماموریت و ...) 4- مدیریت عملکرد مالی (مدیریت پرداخت ها شامل حقوق، مساعده، وام و ... ) 5- و ... چهار بخش اشاره شده برای ما توی اولویت هستن.
> 
> حالا بر اساس توضیحات اولیه بالا میتونیم یه بخش کوچکتری رو انتخاب کنیم و روی اون پیش بریم. لطفا هر کسی نظرش رو بگه و اگه نیاز به توضیحات بیشتر هست بگین تا روشنتر بشه موضوع. حتی به نظرم مفاهیم جلسه دوم (دامنه و زیر دامنه) رو میشه روی همین توضیحاتی که دادم پیش ببریم و یکی از زیر دامنه هایی که تشخیص میدیم رو برای مفاهیم جلسات بعدی انتخاب کنیم.

تشکیل پرونده پرسنلی بنظر من خوبه، فکر کنم خیلی ساده می تونیم عناوین DDD رو باهاش پوشش بدیم.

**Comment by niloo90** [comment]
منم با بخش پرسنلی موافقم، مفاهیم ملموستر و اجرایی تری داره

**Comment by hadisadibkia** [comment]
نیلوفر جانم بنظرم تشکیل پرونده پرسنلی ملموس تر و کوچیکتره برای شروع.

**Comment by hamedebtekar** [comment]
بنظر من اصلا ابتدای پروژه منابع انسانی که خب حالا تمرکز روی مسائل مربوط به حضور پرسنل هست بصورت قطعی روی تعریف و تشکیل پرونده پرسنل هست و تمامی موارد دیگر که شرح دادید بر اساس همین اطلاعات پرونده پیش خواهند رفت ، در این پروژه دامنه اصلی (core domain)روی پرسنل هست و و تمامی موارد مانند حکم و حقوق و محاسبات عیدی و .. هم جزئی از این دامنه  هستند و میشه بعنوان زیر دامنه باشن ،(اساسا اینجا تعریف دامنه و زیر دامنه ضمنی و به هدف ما بر میگرده یک دامنه ممکنه یک زیر دامنه باشه و برعکس) و sub domain ها یا دامنه های دیگر  این پروژه همون پروسه های قبل ورود ،هنگام ورود و خروج پرسنل میشه .suppoted domain ها هم میشه سیستم finance, و budget  که در خصوص صدور اسناد از سیستم حقوق به سیستم مالی و بودجه می باشد. البته در core ما بخش های مختلف سیستم مانند تمام محاسبات (حقوق ،عیدی، فوق العاده ها، امتیاز بندی ها و ...) رو داریم که اینا به تفکیک بصورت سرویس های جداگانه پیاده سازی خواهند شد.

**Comment by zohrehzamani** [comment]
من هم با نظر نبی و حدیث موافقم که از تشکیل پرونده شروع کنیم. به نظرم موضوع خیلی شفاف و قابل درک هست.

**Comment by Amirrewz** [comment]
به نظر منم‌تشکیل پرونده پرسنلی بهتره
فهمش عامیانه هست فکر کنم.
فقط بقیه موارد گفته شده نیاز به دانش‌ بیزینسی‌ نیست؟
